"""Add is_available and discount_percent to menu_items

Revision ID: 6e4bbf45d86e
Revises: d5832f98411c
Create Date: 2026-08-29 14:24:00.344338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e4bbf45d86e'
down_revision = 'd5832f98411c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_available', sa.Boolean(), server_default='true', nullable=False))
        batch_op.add_column(sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_column('discount_percent')
        batch_op.drop_column('is_available')

    # ### end Alembic commands ###
